Update redis urls in example .env
mendableai/firecrawl pull request #515
Opened 2024-08-09 16:53 UTC by wahpiangle

Closes #514

2024-08-09 17:09 UTC, nickscamara commented
Thank you @wahpiangle!

2024-08-09 17:13 UTC, wahpiangle commented
Thanks for this awesome project btw @nickscamara Keep up the good work!

2024-08-09 18:43 UTC, rafaelsideguide requested changes
`redis://redis:6379` is used for Docker. For running without Docker, contributors should use `redis://localhost:6379`. @wahpiangle , since the [self host guide](https://github.com/mendableai/firecrawl/blob/main/SELF_HOST.md) directs contributors to use Docker, could we retain the localhost configuration as a comment in the `.env` file?

2024-08-12 13:37 UTC, rafaelsideguide approved these changes

2024-08-12 20:51 UTC, merged