feat: Support environments without ws by dynamically importing WebSocket module with error handling
mendableai/firecrawl pull request #997
Opened 2024-12-19 12:54 UTC by tomkosm

2024-12-19 14:01 UTC, mogery requested changes

2024-12-19 14:01 UTC, mogery commented on apps/js-sdk/firecrawl/src/index.ts
> +    console.error("Failed to load 'isows' module:", error);
Let's not log this.

2024-12-19 19:39 UTC, mogery approved these changes

2024-12-19 20:02 UTC, tomkosm commented
> blocked by fc side, will merge then

Why is it blocked? Dont merge yet need to do some more testing

2024-12-21 00:33 UTC, tomkosm commented
@mogery @rafaelsideguide should be good to go, added testing and fixed some tests that were broken

2024-12-23 21:41 UTC, merged

2024-12-23 21:44 UTC, nickscamara commented
```CJS Build failed
Error: Build failed with 1 error:
src/index.ts:12:48: ERROR: Top-level await is currently not supported with the "cjs" output format
    at addChunk (node:internal/streams/readable:368:12)```